import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1c1b1b",
        "inverse-primary": "#5d5f5f",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#474747",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed": "#1b1b1b",
        "surface-container-highest": "#353535",
        "primary-container": "#e2e2e2",
        "background": "#131313",
        "surface-bright": "#393939",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-container": "#636565",
        "on-surface-variant": "#c4c7c8",
        "tertiary-fixed": "#e2e2e2",
        "inverse-surface": "#e5e2e1",
        "surface": "#131313",
        "secondary": "#c6c6c6",
        "surface-variant": "#353535",
        "primary-fixed-dim": "#c6c6c7",
        "on-primary": "#2f3131",
        "on-surface": "#e5e2e1",
        "outline-variant": "#444748",
        "on-tertiary-fixed-variant": "#454747",
        "on-secondary-container": "#b5b5b5",
        "on-background": "#e5e2e1",
        "on-tertiary": "#2f3131",
        "primary-fixed": "#e2e2e2",
        "error-container": "#93000a",
        "secondary-fixed": "#e2e2e2",
        "on-primary-fixed": "#1a1c1c",
        "secondary-container": "#474747",
        "on-error": "#690005",
        "on-tertiary-container": "#636565",
        "on-primary-fixed-variant": "#454747",
        "surface-container": "#20201f",
        "tertiary": "#ffffff",
        "on-tertiary-fixed": "#1a1c1c",
        "primary": "#ffffff",
        "inverse-on-surface": "#313030",
        "outline": "#8e9192",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#c6c6c6",
        "surface-tint": "#c6c6c7",
        "surface-dim": "#131313",
        "on-secondary": "#303030",
        "tertiary-container": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "section-gap": "8rem",
        "gutter": "1.5rem",
        "element-gap": "2rem",
        "margin-edge": "2rem",
      },
      fontFamily: {
        "display-xl": ["var(--font-epilogue)"],
        "headline-md": ["var(--font-epilogue)"],
        "body-sm": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "label-caps": ["var(--font-inter)"],
        "headline-lg": ["var(--font-epilogue)"],
      },
      fontSize: {
        "display-xl": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-sm": [
          "14px",
          { lineHeight: "1.5", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.2em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
